### ISSUE TITLE
Double role main

### ISSUE THREAD

**Issue by marlara** [Daniel-KM/Omeka-S-module-Search#3]
I don't know if I'm using it incorrectly, but it seems to me that using the module it appears a double `id="content" role="main"` in the page. Probably the part of the code that is giving this issue is there?

line 58-60 in search.phtml

```
<?php if (empty($isPartial)): ?>
<div id="content" role="main">
<?php endif; ?>
```

**Comment by Daniel-KM** [comment]
I don't have this issue. Where do you have it? In fact, it may depend on your theme if you set the div in the layout.

**Comment by Daniel-KM** [comment]
This is fixed!

**Comment by marlara** [comment]
Sorry I didn't see the message. Thanks

**Comment by marlara** [comment]
I'm truly sorry for this, but when installing the new model I get:

_An exception occurred while executing 'CREATE TABLE `search_index` ( `id` INT AUTO_INCREMENT NOT NULL, `name` VARCHAR(190) NOT NULL, `adapter` VARCHAR(190) NOT NULL, `settings` LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json)', `created` DATETIME NOT NULL, `modified` DATETIME DEFAULT NULL, PRIMARY KEY(`id`) ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'search_index' already exist_

I had uninstalled and removed the previous version of the module before installing the new one

**Comment by Daniel-KM** [comment]
There was probably an issue when uninstalling the module: the table is still there. 
If you have access to the database, you can uninstall it manually:
```sql
DROP TABLE IF EXISTS `search_page`;
DROP TABLE IF EXISTS `search_index`;
```

**Comment by marlara** [comment]
Mh, I've done it, but now it always gives me this message. I removed it and dropped the tables again to see if something went better, then reinstalled, but nothing changes

```
Laminas\Router\Exception\RuntimeException
Route with name "search" not found

Deatils:

Laminas\Router\Exception\RuntimeException: Route with name "search" not found in /var/www/html/omeka-s/vendor/laminas/laminas-router/src/Http/TreeRouteStack.php:355
```

**Comment by Daniel-KM** [comment]
This issue is not related to the tables and is strange. Is it in admin ?

**Comment by marlara** [comment]
It is in the admin/module page, when installing the module

**Comment by Daniel-KM** [comment]
Thanks, the install is fixed.
