### ISSUE TITLE
Sort functionality doesn't work

### ISSUE THREAD

**Issue by Falteri** [Daniel-KM/Omeka-S-module-Search#4]
Hi Daniel,
I see this has been already fixed and closed (https://gitlab.com/Daniel-KM/Omeka-S-module-Search/-/issues/2), but it seems I still have some related problems as I'm not able to let the sort working. What is happening to me is that the drop down list for sorting doesn't have any effect when one change the value. It is like the change doesn't trigger any action. Do you have any suggestion or experience in such problem?

**Comment by Falteri** [comment]
Tou can take a look here: https://banchedati.istitutodegliinnocenti.it/s/sidopsia/simple-search?q=
FYI: module has been updated to the latest version

**Comment by Daniel-KM** [comment]
Yes, it seems that the js is not loaded, so can you add [this to your theme](https://gitlab.com/Daniel-KM/Omeka-S-module-Search/-/blob/master/view/search/index/search.phtml#L57-58) (in the main layout).

**Comment by Falteri** [comment]
Sorry for the delay and thanks for the reply. I moved from Search to AdvancedSearch as you suggest in the page of Search plugin so I will need to chech the js for that new module. But now I've other problems with that module that I need to understand. I will post those issue in the appropriate project and then, once solved, I will test the sort fix you suggest here and then  close this thread.
Many thanks!
